### PR TITLE
Communicationweek5

### PR DESCRIPTION
**Pull request by minjupgeorge**
## General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work

### HTML

- [ ] pages besides `/index.html` are stored in `/pages`
- [ ] the code is well-formatted
- [ ] the HTML is valid
- [ ] there are no inline styles (example: `style='color: red;'`)
- [ ] there are no `<style>` tags with CSS, all styles are hrefs
- [ ] there is no inline JavaScript (example: `onclick='doSomething()'`)
- [ ] there are no `<script>` tags with JS, all JS is in an separate file
- [ ] `id`s are used for JavaScript only, not for CSS
- [ ] semantic tags are used
- [ ] spelling and grammar is correct in all site content

### CSS

- [ ] the code is well-formatted
- [ ] passes all the linting checks

### CODE REVIEW

**Comment by MMikhailova** [comment]
@minjupgeorge Thank you for giving your availability. Could you check the conflict please so we can merge.

**Comment by danielhalasz** [comment]
hi @minjupgeorge it seems like this PR changes 10 files, although it is just called communication week 5..
is this intentional? if so, it is better it into separate the PRs

**Review by danielhalasz — CHANGES_REQUESTED** [review]
see my comment in the PR

**Comment by minjupgeorge** [comment]
@MMikhailova @danielhalasz I have resolved the conflicts .

**Comment by danielhalasz** [comment]
that's nice! are the other files besides the communication plan intentionally in the same PR? why?

**Comment by minjupgeorge** [comment]
@danielhalasz No . I have created this branch last week before those changes. For every change there is another pull request.

**Comment by danielhalasz** [comment]
> @danielhalasz No . I have created this branch last week before those changes. For every change there is another pull request.

well, there are new files in this PR not related to the communication.md ... so this is not the best practice.. but for now, it can be approved, just try to avoid it in the future.. and please fix the merge conflict, thanks

**Comment by minjupgeorge** [comment]
@danielhalasz I have updated those changes with another PR which was not merged due to incomplete features. 
image

Then I have created communicationweek5 update in another branch. Those commits were followed here too.

**Comment by danielhalasz** [comment]
@minjupgeorge pls solve the merge conflict

**Comment by danielhalasz** [comment]
or let us know if you need help with that

**Comment by minjupgeorge** [comment]
@MMikhailova @danielhalasz I have resolved the conflicts.

**Review by danielhalasz — APPROVED** [review]

**Pull request merged**
