### PR TITLE
Navigationbar

### PR DESCRIPTION
**Pull request by minjupgeorge**
## General Checks

- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] All CI checks pass
- [ ] all conflicts are resolved (if any)
- [ ] PR has a descriptive title
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [ ] reviewers are assigned
- [ ] the PR contributes only one focused change
- [ ] It is in the appropriate column in the project board (if necessary)
- [ ] has short and clear description
- [ ] is linked to an issue (if it is related)
- [ ] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [ ] the markdown source is formatted
- [ ] spelling and grammar is correct in all text
- [ ] The markdown looks correct when you preview the file
- [ ] all links and images work

### HTML

- [ ] pages besides `/index.html` are stored in `/pages`
- [ ] the code is well-formatted
- [ ] the HTML is valid
- [ ] there are no inline styles (example: `style='color: red;'`)
- [ ] there are no `<style>` tags with CSS, all styles are hrefs
- [ ] there is no inline JavaScript (example: `onclick='doSomething()'`)
- [ ] there are no `<script>` tags with JS, all JS is in an separate file
- [ ] `id`s are used for JavaScript only, not for CSS
- [ ] semantic tags are used
- [ ] spelling and grammar is correct in all site content

### CSS

- [ ] the code is well-formatted
- [ ] passes all the linting checks

### CODE REVIEW

**Review by danielhalasz — CHANGES_REQUESTED** [review]
the first errors that I get are these:

```src/components/Header.jsx
  Line 18:9:   'isMatch' is assigned a value but never used                                                               no-unused-vars
  Line 24:13:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text

ERROR in ./src/components/Header.jsx 9:0-56
Module not found: Error: Can't resolve '@mui/icons-material/Business' in '/Users/daniel/HYF/HYF-Lab-Brussels-1/Job-Advisor/FrontEnd/react/src/components'

ERROR in ./src/components/Header.jsx 10:0-60
Module not found: Error: Can't resolve '@mui/icons-material/RateReview' in '/Users/daniel/HYF/HYF-Lab-Brussels-1/Job-Advisor/FrontEnd/react/src/components'
```

after manually installing mui icons material package, it works.. is it supposed to look like this?
the images are still distorted and appear to be very low quality, pixelated.

image

**Comment by danielhalasz** [comment]
looking into the Item.jsx, you could try something like this to fix the images:

```
export default function Item({ item, onSelect }) {
  const navigate = useNavigate();
  return (
    <Paper
      onClick={() => {
        onSelect(item.collection);
        navigate("/searchResult");
      }}
    >
      <img
        src={item.image}
        alt={item.title}
        style={{ width: "25vw", display: "flex" }}
      ></img>

      <Button display="flex">{item.title}</Button>
    </Paper>
  );
}
```

**Comment by minjupgeorge** [comment]
@danielhalasz I have updated the code and now its looks better
image

**Review by danielhalasz — APPROVED** [review]

**Comment by minjupgeorge** [comment]
I have updated the ground image too
image

**Pull request merged**
